# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DeHazeImage.ui'
#
# Created: Sat Apr 11 21:24:28 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DeHazeImage(object):
    def setupUi(self, DeHazeImage):
        DeHazeImage.setObjectName(_fromUtf8("DeHazeImage"))
        DeHazeImage.setWindowModality(QtCore.Qt.NonModal)
        DeHazeImage.resize(349, 377)
        DeHazeImage.setFocusPolicy(QtCore.Qt.NoFocus)
        DeHazeImage.setModal(False)
        self.buttonBox = QtGui.QDialogButtonBox(DeHazeImage)
        self.buttonBox.setGeometry(QtCore.QRect(150, 340, 176, 27))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.layoutWidget = QtGui.QWidget(DeHazeImage)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 120, 299, 89))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.labelExtents = QtGui.QLabel(self.layoutWidget)
        self.labelExtents.setObjectName(_fromUtf8("labelExtents"))
        self.verticalLayout_5.addWidget(self.labelExtents)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEditMinX = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditMinX.setObjectName(_fromUtf8("lineEditMinX"))
        self.gridLayout.addWidget(self.lineEditMinX, 0, 0, 1, 1)
        self.lineEditMinY = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditMinY.setObjectName(_fromUtf8("lineEditMinY"))
        self.gridLayout.addWidget(self.lineEditMinY, 1, 1, 1, 1)
        self.lineEditMaxX = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditMaxX.setObjectName(_fromUtf8("lineEditMaxX"))
        self.gridLayout.addWidget(self.lineEditMaxX, 1, 0, 1, 1)
        self.lineEditMaxY = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditMaxY.setObjectName(_fromUtf8("lineEditMaxY"))
        self.gridLayout.addWidget(self.lineEditMaxY, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtGui.QWidget(DeHazeImage)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 11, 299, 56))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.layerLabel = QtGui.QLabel(self.layoutWidget1)
        self.layerLabel.setObjectName(_fromUtf8("layerLabel"))
        self.verticalLayout_3.addWidget(self.layerLabel)
        self.layerComboBox = QtGui.QComboBox(self.layoutWidget1)
        self.layerComboBox.setObjectName(_fromUtf8("layerComboBox"))
        self.verticalLayout_3.addWidget(self.layerComboBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labelBlueBand = QtGui.QLabel(self.layoutWidget1)
        self.labelBlueBand.setObjectName(_fromUtf8("labelBlueBand"))
        self.verticalLayout.addWidget(self.labelBlueBand)
        self.blueComboBox = QtGui.QComboBox(self.layoutWidget1)
        self.blueComboBox.setObjectName(_fromUtf8("blueComboBox"))
        self.verticalLayout.addWidget(self.blueComboBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelRedBand = QtGui.QLabel(self.layoutWidget1)
        self.labelRedBand.setObjectName(_fromUtf8("labelRedBand"))
        self.verticalLayout_2.addWidget(self.labelRedBand)
        self.redComboBox = QtGui.QComboBox(self.layoutWidget1)
        self.redComboBox.setObjectName(_fromUtf8("redComboBox"))
        self.verticalLayout_2.addWidget(self.redComboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.label_5 = QtGui.QLabel(DeHazeImage)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 161, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.layoutWidget2 = QtGui.QWidget(DeHazeImage)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 240, 257, 29))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.radioButtonMean = QtGui.QRadioButton(self.layoutWidget2)
        self.radioButtonMean.setObjectName(_fromUtf8("radioButtonMean"))
        self.horizontalLayout_5.addWidget(self.radioButtonMean)
        self.radioButtonPercentile = QtGui.QRadioButton(self.layoutWidget2)
        self.radioButtonPercentile.setChecked(True)
        self.radioButtonPercentile.setObjectName(_fromUtf8("radioButtonPercentile"))
        self.horizontalLayout_5.addWidget(self.radioButtonPercentile)
        self.doubleSpinPerc = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinPerc.setMaximum(100.0)
        self.doubleSpinPerc.setProperty("value", 5.0)
        self.doubleSpinPerc.setObjectName(_fromUtf8("doubleSpinPerc"))
        self.horizontalLayout_5.addWidget(self.doubleSpinPerc)
        self.layoutWidget3 = QtGui.QWidget(DeHazeImage)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 80, 301, 29))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBoxMask = QtGui.QCheckBox(self.layoutWidget3)
        self.checkBoxMask.setObjectName(_fromUtf8("checkBoxMask"))
        self.horizontalLayout_6.addWidget(self.checkBoxMask)
        self.comboBoxMask = QtGui.QComboBox(self.layoutWidget3)
        self.comboBoxMask.setObjectName(_fromUtf8("comboBoxMask"))
        self.horizontalLayout_6.addWidget(self.comboBoxMask)
        self.layoutWidget4 = QtGui.QWidget(DeHazeImage)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 281, 311, 44))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_3 = QtGui.QLabel(self.layoutWidget4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.label_6 = QtGui.QLabel(self.layoutWidget4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.spinBoxPolyDeg = QtGui.QSpinBox(self.layoutWidget4)
        self.spinBoxPolyDeg.setMinimum(1)
        self.spinBoxPolyDeg.setMaximum(30)
        self.spinBoxPolyDeg.setObjectName(_fromUtf8("spinBoxPolyDeg"))
        self.horizontalLayout_4.addWidget(self.spinBoxPolyDeg)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_4 = QtGui.QLabel(self.layoutWidget4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_7.addWidget(self.label_4)
        self.label_7 = QtGui.QLabel(self.layoutWidget4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.spinBoxScaling = QtGui.QSpinBox(self.layoutWidget4)
        self.spinBoxScaling.setMinimum(1)
        self.spinBoxScaling.setMaximum(100000)
        self.spinBoxScaling.setObjectName(_fromUtf8("spinBoxScaling"))
        self.horizontalLayout_4.addWidget(self.spinBoxScaling)

        self.retranslateUi(DeHazeImage)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DeHazeImage.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DeHazeImage.reject)
        QtCore.QMetaObject.connectSlotsByName(DeHazeImage)

    def retranslateUi(self, DeHazeImage):
        DeHazeImage.setWindowTitle(_translate("DeHazeImage", "DeHazeImage", None))
        self.labelExtents.setText(_translate("DeHazeImage", "Clear Sky Extents", None))
        self.label.setText(_translate("DeHazeImage", "UL:", None))
        self.label_2.setText(_translate("DeHazeImage", "LR:", None))
        self.lineEditMinX.setText(_translate("DeHazeImage", "217000", None))
        self.lineEditMinY.setText(_translate("DeHazeImage", "845000", None))
        self.lineEditMaxX.setText(_translate("DeHazeImage", "229000", None))
        self.lineEditMaxY.setText(_translate("DeHazeImage", "852000", None))
        self.layerLabel.setText(_translate("DeHazeImage", "Input Layer", None))
        self.labelBlueBand.setText(_translate("DeHazeImage", "Blue band", None))
        self.labelRedBand.setText(_translate("DeHazeImage", "Red band", None))
        self.label_5.setText(_translate("DeHazeImage", "CL-HOT Matching Stat", None))
        self.radioButtonMean.setText(_translate("DeHazeImage", "Mean", None))
        self.radioButtonPercentile.setText(_translate("DeHazeImage", "Percentile", None))
        self.checkBoxMask.setText(_translate("DeHazeImage", "Mask (Water, etc.)", None))
        self.label_3.setText(_translate("DeHazeImage", "Correction", None))
        self.label_6.setText(_translate("DeHazeImage", "Function Deg.", None))
        self.spinBoxPolyDeg.setWhatsThis(_translate("DeHazeImage", "Degree of Correction Function. e.g. 1 -> linear", None))
        self.label_4.setText(_translate("DeHazeImage", "Value ", None))
        self.label_7.setText(_translate("DeHazeImage", "scaling", None))
        self.spinBoxScaling.setWhatsThis(_translate("DeHazeImage", "Degree of Correction Function. e.g. 1 -> linear", None))

